//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupifyApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Track()
        {
            this.MusicConnections = new HashSet<MusicConnections>();
        }
    
        public int Id { get; set; }
        public string trackid { get; set; }
        public int userid { get; set; }
        public Nullable<int> times_lstened { get; set; }
        public Nullable<System.DateTime> added_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusicConnections> MusicConnections { get; set; }
        public virtual Users Users { get; set; }
    }
}
